name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Fix for missing or corrupted gradle-wrapper.jar
    - name: Setup Gradle Wrapper
      run: |
        mkdir -p gradle/wrapper
        curl -L -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.2.0/gradle/wrapper/gradle-wrapper.jar
        echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
        echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        chmod +x gradlew
 
    - name: Display project structure
      run: |
        echo "Project structure:"
        ls -la
        echo "Gradle Wrapper:"
        ls -la gradle/wrapper/

    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2
        
    - name: Build with Gradle (with detailed logs)
      run: ./gradlew build --info
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --info
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build Release APK
      run: ./gradlew assembleRelease --info
      
    - name: Sign Release APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        
    - name: Archive Build Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          app/build/reports/
          build/reports/